# 4)ARRAYOPERATIONS

In [5]:
import numpy as np
array1=np.arange(1,15)
print("The array is:",array1)
print("The array size is:",array1.size)
array1[8]=99
print("The updated array is:",array1)
print("Reverse array:",array1[::-1])

print("The array as a 7*2 matrix is:",array1.reshape(7,2))



The array is: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The array size is: 14
The updated array is: [ 1  2  3  4  5  6  7  8 99 10 11 12 13 14]
Reverse array: [14 13 12 11 10 99  8  7  6  5  4  3  2  1]
The array as a 7*2 matrix is: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [99 10]
 [11 12]
 [13 14]]


# 5) matrix  shape,type and datatype

In [10]:
import numpy as np

array2=np.arange(12,32)
array3=array2.reshape(5,4)
print("5*4 matrix :\n",array3)
print("Matrix type:",type(array3))
print("Matrix datatype:",array3.dtype)

5*4 matrix :
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Matrix type: <class 'numpy.ndarray'>
Matrix datatype: int64


# 6) CHECKBOARD PATTERN

In [13]:
import numpy as np
arr1=np.zeros((8,8),dtype=int)
arr1[::2,1::2]=1
arr1[1::2,::2]=1
print(arr1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 7) CHECKING ELEMENTS IN A 1-D array

In [14]:
import numpy as np

ar1=([1,2,3,4,5,6])
ar2=([4,5,6])
print("Comparing the 2 arrays:",np.in1d(ar1,ar2))

Comparing the 2 arrays: [False False False  True  True  True]


# 8) INTERSECTION AND UNION OF ARRAYS

In [15]:
import numpy as np
a1=([10,20,40,50])
a2=([30,20])
print("Arrays are :\n",a1,"\n",a2)
print("Common elements are:",np.intersect1d(a1,a2))
print("Union:",np.union1d(a1,a2))

Arrays are :
 [10, 20, 40, 50] 
 [30, 20]
Common elements are: [20]
Union: [10 20 30 40 50]


# 9) Unique elements of an array

In [17]:
import numpy as np

my_array1=np.array([10,20,10,30,20,50,50,10])
print("The array is :",my_array1)
print("Unique elemets are:",np.unique(my_array1))

The array is : [10 20 10 30 20 50 50 10]
Unique elemets are: [10 20 30 50]


# 10) ARRAY TO LIST CONVERSION 

In [18]:
import numpy as np
my_array2=np.array([10,20,30,40])
print("The array is:",my_array2)
print("The array type is:",type(my_array2))

list1=my_array2.tolist()
print("The list is ",list1)
print("The type is :",type(list))

The array is: [10 20 30 40]
The array type is: <class 'numpy.ndarray'>
The list is  [10, 20, 30, 40]
The type is : <class 'type'>


# EXTRA Q 1

In [22]:
import numpy as np
checkarr=np.zeros((8,8),dtype=int)
checkarr[::2,::4]=1
checkarr[::2,1::4]=1

checkarr[1::2,3::4]=1
checkarr[1::2,2::4]=1
print(checkarr)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


# EXTRA Q2

In [14]:
import numpy as np
checkarr=np.zeros((8,8),dtype=int)
checkarr[::2,4::]=1
checkarr[1::2,:4:]=1
print(checkarr)

[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


#  11)Write a numpy program to get unique elements of an array

In [2]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
