## NAME :DURGA PS
## Exp No : 2
## Exp Name : Numpt matrix operations-2
## Experiment completed on :19-08-2022

# 12)Write a program to convert numpy array to python list structure


In [1]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# 13 ) ACCESS AN ARRAY BY COLUMN

In [10]:
import numpy as np

array1=np.arange(11,21).reshape(5,2)
print(array1,"\n\n")

#accesing the colum 2

print("First column:",array1[:,0])

print("Second column:",array1[:,1])

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] 


First column: [11 13 15 17 19]
Second column: [12 14 16 18 20]


# 14) MATRIX MULTIPLICATION AND  ADDITION

In [2]:
import numpy as np

matrix1=np.arange(1,10).reshape(3,3)
matrix2=np.arange(11,20).reshape(3,3)

print("First matrix: \n\n",matrix1)
print("\nSecond matrix: \n\n",matrix2)

matrix3=np.dot(matrix1,matrix2)

matrix4=np.add(matrix1,matrix2)

print("\nThe resultant multiplied matrix:\n\n",matrix3)

print("\nThe addition of the abpve matrices:\n\n",matrix4)


First matrix: 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second matrix: 

 [[11 12 13]
 [14 15 16]
 [17 18 19]]

The resultant multiplied matrix:

 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]

The addition of the abpve matrices:

 [[12 14 16]
 [18 20 22]
 [24 26 28]]


# 15) EIGEN VALUES AND EIGEN VECTORS

In [22]:
import numpy as np

a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)

print("Eigenvalues are:",w)
print("EIgen vectors are:\n\n",v)

Eigenvalues are: [4. 1.]
EIgen vectors are:

 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


# 16) DETERMINANT ,INVERSE AND TRANSPOSEOF A MATRIX

In [37]:
import numpy as np

my_array=np.array([[50,29],[30,44]]).reshape(2,2)
print("The original matrix is :\n\n",my_array)
x=np.linalg.det(my_array)
print("\nDETERMINANT IS:\n",int(x))

print("\nTRANSPOSE:\n",np.transpose(my_array))

print("\nINVESRSE:\n",np.linalg.inv(my_array))

The original matrix is :

 [[50 29]
 [30 44]]

DETERMINANT IS:
 1330

TRANSPOSE:
 [[50 30]
 [29 44]]

INVESRSE:
 [[ 0.03308271 -0.02180451]
 [-0.02255639  0.03759398]]
